install.packages("stringr")
install.packages("ggplot2")
install.packages("grid")
install.packages("gridExtra")
install.packages("dplyr")
install.packages("tidyr")
install.packages("foreach")
install.packages("doParallel")
install.packages("data.table")
# install.packages(matrixStats)
install.packages("ggthemes")
install.packages("reshape2")
install.packages("tseries")
install.packages("urca")
install.packages("forecast")
install.packages("pracma")
# install.packages("ggpubr")
install.packages("cowplot")
install.packages("ggnewscale")
install.packages("xtable")
